## Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean , transform and extract insights from data

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('output.csv')

## Fetch the first 5 rows
df.head()

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,Feature11,Feature12,Feature13,Feature14,Feature15,Feature16,Feature17,Feature18,Feature19,Feature20
0,44.0,0.797417,-0.958091,NaN,NaN,158.0,1.490148,5.166124,2.277942,NaN,5,X,1,Category1,Option4,8.824345,11.711130,Yes,Low,NaN
1,47.0,0.026838,-0.244178,D,NaN,NaN,2.151535,0.450312,-3.395356,NaN,3,X,0,Category1,Option2,NaN,13.355832,Yes,Low,cat
2,64.0,0.199990,-1.014799,B,0.0,474.0,1.410613,6.786555,-3.070746,NaN,7,Z,0,Category1,Option2,NaN,13.449484,Yes,Medium,dog
3,67.0,0.474124,0.448040,B,NaN,166.0,0.635091,1.937158,-0.246269,6.004975,20,X,0,Category1,Option2,NaN,7.687652,Yes,Low,cat
4,NaN,0.598516,0.087839,NaN,0.0,NaN,0.392104,4.010937,3.215086,2.891199,3,Z,0,Category1,Option3,11.259371,6.807770,Yes,Low,cat

In [4]:
df.tail(5)

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,Feature11,Feature12,Feature13,Feature14,Feature15,Feature16,Feature17,Feature18,Feature19,Feature20
4995,NaN,0.819440,0.415931,C,0.0,NaN,1.765590,1.929735,-1.951884,NaN,1,Z,1,Category2,Option4,NaN,14.821501,No,Low,NaN
4996,NaN,0.032140,-1.445420,C,1.0,NaN,0.806246,8.765315,-1.866815,NaN,1,Y,0,Category3,Option4,6.368173,5.308922,Yes,Medium,NaN
4997,92.0,0.263300,0.986722,C,NaN,78.0,1.326853,4.489722,1.720671,6.877962,1,X,0,Category1,Option4,5.682022,9.508951,Yes,Medium,NaN
4998,91.0,0.640986,-1.199847,A,0.0,51.0,0.312256,2.773963,-3.320704,6.138322,2,X,0,Category1,Option3,4.574748,8.705127,No,Medium,some other
4999,NaN,0.901570,1.836382,NaN,0.0,NaN,2.087461,6.854886,-0.259228,6.068139,6,X,0,Category2,Option2,12.801075,14.686372,Yes,High,some other

In [5]:
df.describe()

,Feature1,Feature2,Feature3,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,Feature11,Feature13,Feature16,Feature17
count,2296.000000,5000.000000,5000.000000,2968.000000,3016.000000,5000.000000,4899.000000,5000.000000,2164.000000,5000.000000,5000.000000,2994.000000,5000.000000
mean,48.102787,0.509843,-0.009058,0.103774,506.703346,0.993603,3.996315,-0.024540,4.998186,4.967800,0.496000,10.042781,9.996307
std,28.605603,0.322480,1.010739,0.305018,351.183479,0.991321,2.811892,1.829975,2.289341,4.571624,0.674444,1.990496,2.893759
min,0.000000,-0.476438,-3.644316,0.000000,-538.762910,0.000775,0.033463,-8.516517,-0.215454,1.000000,0.000000,3.627312,5.000292
25%,24.000000,0.253741,-0.686737,0.000000,220.000000,0.286745,1.905678,-1.124829,3.113014,2.000000,0.000000,8.735518,7.509306
50%,47.000000,0.513507,-0.017156,0.000000,507.679700,0.702917,3.360472,0.008667,4.936186,4.000000,0.000000,10.038727,10.026013
75%,72.000000,0.770195,0.688604,0.000000,784.000000,1.376030,5.380483,1.107796,6.175253,7.000000,1.000000,11.385440,12.485023
max,99.000000,1.497998,3.422062,1.000000,1543.622087,8.843108,22.813462,9.915071,14.060631,46.000000,2.000000,17.012344,14.999633

In [7]:
df.dtypes

Feature1     float64
Feature2     float64
Feature3     float64
Feature4         str
Feature5     float64
Feature6     float64
Feature7     float64
Feature8     float64
Feature9     float64
Feature10    float64
Feature11      int64
Feature12        str
Feature13      int64
Feature14        str
Feature15        str
Feature16    float64
Feature17    float64
Feature18        str
Feature19        str
Feature20        str
dtype: object

In [7]:
df.isnull().sum()

Feature1     2704
Feature2        0
Feature3        0
Feature4     1868
Feature5     2032
Feature6     1984
Feature7        0
Feature8      101
Feature9        0
Feature10    2836
Feature11       0
Feature12       0
Feature13       0
Feature14       0
Feature15       0
Feature16    2006
Feature17       0
Feature18       0
Feature19     295
Feature20    1733
dtype: int64

In [8]:
df.fillna(0)

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,Feature11,Feature12,Feature13,Feature14,Feature15,Feature16,Feature17,Feature18,Feature19,Feature20
0,44.0,0.797417,-0.958091,0,0.0,158.0,1.490148,5.166124,2.277942,0.000000,5,X,1,Category1,Option4,8.824345,11.711130,Yes,Low,0
1,47.0,0.026838,-0.244178,D,0.0,0.0,2.151535,0.450312,-3.395356,0.000000,3,X,0,Category1,Option2,0.000000,13.355832,Yes,Low,cat
2,64.0,0.199990,-1.014799,B,0.0,474.0,1.410613,6.786555,-3.070746,0.000000,7,Z,0,Category1,Option2,0.000000,13.449484,Yes,Medium,dog
3,67.0,0.474124,0.448040,B,0.0,166.0,0.635091,1.937158,-0.246269,6.004975,20,X,0,Category1,Option2,0.000000,7.687652,Yes,Low,cat
4,0.0,0.598516,0.087839,0,0.0,0.0,0.392104,4.010937,3.215086,2.891199,3,Z,0,Category1,Option3,11.259371,6.807770,Yes,Low,cat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.0,0.819440,0.415931,C,0.0,0.0,1.765590,1.929735,-1.951884,0.000000,1,Z,1,Category2,Option4,0.000000,14.821501,No,Low,0
4996,0.0,0.032140,-1.445420,C,1.0,0.0,0.806246,8.765315,-1.866815,0.000000,1,Y,0,Category3,Option4,6.368173,5.308922,Yes,Medium,0
4997,92.0,0.263300,0.986722,C,0.0,78.0,1.326853,4.489722,1.720671,6.877962,1,X,0,Category1,Option4,5.682022,9.508951,Yes,Medium,0
4998,91.0,0.640986,-1.199847,A,0.0,51.0,0.312256,2.773963,-3.320704,6.138322,2,X,0,Category1,Option3,4.574748,8.705127,No,Medium,some other
4999,0.0,0.901570,1.836382,0,0.0,0.0,2.087461,6.854886,-0.259228,6.068139,6,X,0,Category2,Option2,12.801075,14.686372,Yes,High,some other

In [ ]:
df.isnull().sum

<bound method DataFrame.sum of       Feature1  Feature2  Feature3  Feature4  Feature5  Feature6  Feature7  \
0        False     False     False      True      True     False     False
1        False     False     False     False      True      True     False
2        False     False     False     False     False     False     False
3        False     False     False     False      True     False     False
4         True     False     False      True     False      True     False
...        ...       ...       ...       ...       ...       ...       ...
4995      True     False     False     False     False      True     False
4996      True     False     False     False     False      True     False
4997     False     False     False     False      True     False     False
4998     False     False     False     False     False     False     False
4999      True     False     False      True     False      True     False

      Feature8  Feature9  Feature10  Feature11  Feature12  Feature13  \
0        False     False       True      False      False      False
1        False     False       True      False      False      False
2        False     False       True      False      False      False
3        False     False      False      False      False      False
4        False     False      False      False      False      False
...        ...       ...        ...        ...        ...        ...
4995     False     False       True      False      False      False
4996     False     False       True      False      False      False
4997     False     False      False      False      False      False
4998     False     False      False      False      False      False
4999     False     False      False      False      False      False

      Feature14  Feature15  Feature16  Feature17  Feature18  Feature19  \
0         False      False      False      False      False      False
1         False      False       True      False      False      False
2         False      False       True      False      False      False
3         False      False       True      False      False      False
4         False      False      False      False      False      False
...         ...        ...        ...        ...        ...        ...
4995      False      False       True      False      False      False
4996      False      False      False      False      False      False
4997      False      False      False      False      False      False
4998      False      False      False      False      False      False
4999      False      False      False      False      False      False

      Feature20
0          True
1         False
2         False
3         False
4         False
...         ...
4995       True
4996       True
4997       True
4998      False
4999      False

[5000 rows x 20 columns]>